services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user-service
      - catalog-service-1
      - catalog-service-2
      - playlist-service-1
      - playlist-service-2
    networks:
      - streamline-network

  mongo-users:
    image: mongo:7
    container_name: mongo-users
    volumes:
      - mongo-users-data:/data/db
    networks:
      - streamline-network

  mongo-catalog:
    image: mongo:7
    container_name: mongo-catalog
    volumes:
      - mongo-catalog-data:/data/db
    networks:
      - streamline-network

  mongo-playlists:
    image: mongo:7
    container_name: mongo-playlists
    volumes:
      - mongo-playlists-data:/data/db
    networks:
      - streamline-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - PORT=8081
      - MONGODB_URI=mongodb://mongo-users:27017/streamline-users
      - JWT_SECRET=a7cc916f35d26f09ec3af3dee26b2ea8
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - mongo-users
      - notification-service
    networks:
      - streamline-network

  catalog-service-1:
    build: ./catalog-service
    container_name: catalog-service-1
    environment:
      - PORT=8082
      - MONGODB_URI=mongodb://mongo-catalog:27017/streamline-catalog
      - JWT_SECRET=a7cc916f35d26f09ec3af3dee26b2ea8
    depends_on:
      - mongo-catalog
    networks:
      - streamline-network

  catalog-service-2:
    build: ./catalog-service
    container_name: catalog-service-2
    environment:
      - PORT=8082
      - MONGODB_URI=mongodb://mongo-catalog:27017/streamline-catalog
      - JWT_SECRET=a7cc916f35d26f09ec3af3dee26b2ea8
    depends_on:
      - mongo-catalog
    networks:
      - streamline-network

  playlist-service-1:
    build: ./playlist-service
    container_name: playlist-service-1
    environment:
      - PORT=8083
      - MONGODB_URI=mongodb://mongo-playlists:27017/streamline-playlists
      - JWT_SECRET=a7cc916f35d26f09ec3af3dee26b2ea8
      - CATALOG_SERVICE_URL=http://nginx-lb:8080
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - mongo-playlists
      - catalog-service-1
      - catalog-service-2
      - notification-service
    networks:
      - streamline-network

  playlist-service-2:
    build: ./playlist-service
    container_name: playlist-service-2
    environment:
      - PORT=8083
      - MONGODB_URI=mongodb://mongo-playlists:27017/streamline-playlists
      - JWT_SECRET=a7cc916f35d26f09ec3af3dee26b2ea8
      - CATALOG_SERVICE_URL=http://nginx-lb:8080
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - mongo-playlists
      - catalog-service-1
      - catalog-service-2
      - notification-service
    networks:
      - streamline-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - PORT=8084
      - SMTP_HOST=sandbox.smtp.mailtrap.io
      - SMTP_PORT=2525
      - SMTP_USER=90f364d48b9196
      - SMTP_PASS=bb47be858a3b95
    networks:
      - streamline-network

volumes:
  mongo-users-data:
  mongo-catalog-data:
  mongo-playlists-data:

networks:
  streamline-network:
    driver: bridge
